### ISSUE TITLE
Schrodinger's Traffic issue possibly caused by Anarchy 

### ISSUE THREAD

**Issue by zeroibis** [yenyang/Anarchy-BepInEx#14]
https://forum.paradoxplaza.com/forum/threads/schrodingers-traffic.1621003/page-2#post-29384644

It appears that the issue with motorcycles getting stuck when not observed may be related to Anarchy.

Worth investigating as the issue causes traffic to gridlock.

**Comment by yenyang** [comment]
I reviewed the code and could see how that could happen. It was entirely
unintentional and I’m impressed at how much those people figured out about
the problem. I’ll try to work out a solution tomorrow. I already have an
idea of how to approach the problem.

Thank you for the report. I wouldn’t have found out otherwise. I have seen
similar reports but not from people that tied it to anarchy.

**Comment by yenyang** [comment]
Should be resolved with V1.3.0. Thanks again for the report.

**Comment by Lennonmapes** [comment]
The issue still seems to be persisting after the update to my trams. Do you have any ideas on how to resolve this? I tried removing the tram line, deleting the tram tracks, and re-adding the line, but the trams are still getting stuck at the same point.

**Comment by zeroibis** [comment]
> The issue still seems to be persisting after the update to my trams. Do you have any ideas on how to resolve this? I tried removing the tram line, deleting the tram tracks, and re-adding the line, but the trams are still getting stuck at the same point.

I think you are talking about this issue: https://forum.paradoxplaza.com/forum/threads/picking-passengers-on-one-stop-takes-hours.1607658/#post-29241405

That problem is not currently known to be caused by any mod and has existed since the game released.
